server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
        routes:
          - id: user-service
            uri: lb://user-service
            predicates:
              - Path=/users/**
          - id: joboffer-service
            uri: lb://joboffer-service
            predicates:
              - Path=/joboffers/**
          - id: subscription-service
            uri: lb://subscription-service
            predicates:
              - Path=/subscriptions/**
          - id: postulation-service
            uri: lb://postulation-service
            predicates:
              - Path=/postulations/**
          - id: payment-service
            uri: lb://payment-service
            predicates:
              - Path=/payments/**

